version: '3.8'

services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-pass}
      - MYSQL_DATABASE=${DB_NAME:-digbot}
      - MYSQL_USER=${DB_USER:-dig}
      - MYSQL_PASSWORD=${DB_PASS:-pass}
    ports:
      - 3306:3306
  digbot:
    build: .
    depends_on:
      - mariadb
    tty: true
    environment:
      - DISCORD_TOKEN
      - DATABASE_URL=mysql://${DB_USER:-dig}:${DB_PASS:-pass}@mariadb:3306/${DB_NAME:-digbot}

