FROM node:7.6
### Copyright © 2018 DIG Development team. All rights reserved. ###

### Add bash script to Docker image ###
COPY docker/run.sh /app/run.sh

### Bundle source files into the Docker image's app directory ###
COPY . /app
