name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        golang-version: [ 1.20 ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.golang-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.golang-version }}

      - name: Compile
        run: go build -v ./...
